# Generated by Django 4.2.5 on 2023-11-07 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("event", "0035_created_updated_everywhere"),
        ("schedule", "0017_created_updated_everywhere"),
        ("submission", "0074_created_updated_everywhere"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("track_type", models.CharField()),
                ("slug", models.SlugField(max_length=63)),
                ("mail", models.EmailField(default="", max_length=254)),
                ("cfp_url", models.CharField(default="", max_length=254)),
                ("online_qa", models.BooleanField(default=False)),
                (
                    "review_team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="event.team",
                    ),
                ),
                ("rooms", models.ManyToManyField(to="schedule.room")),
                (
                    "track",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submission.track",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackManager",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submission.track",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
