# Generated by Django 4.2.5 on 2023-11-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0017_created_updated_everywhere"),
        ("devroom_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracksettings",
            name="rooms",
            field=models.ManyToManyField(to="schedule.room"),
        ),
    ]
