# Generated by Django 4.2.5 on 2023-11-05 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("event", "0035_created_updated_everywhere"),
        ("devroom_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracksettings",
            name="devroom_managers",
            field=models.ManyToManyField(
                related_name="devroom", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tracksettings",
            name="review_team",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="event.team"
            ),
        ),
    ]
