# Generated by Django 4.2.5 on 2023-11-09 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0035_created_updated_everywhere"),
        ("devroom_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracksettings",
            name="manager_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manager_track",
                to="event.team",
            ),
        ),
        migrations.AlterField(
            model_name="tracksettings",
            name="review_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review_track",
                to="event.team",
            ),
        ),
    ]
