# Generated by Django 4.2.5 on 2023-11-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devroom_settings", "0002_tracksettings_devroom_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracksettings",
            name="track_type",
            field=models.CharField(default="devroom"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tracksettings",
            name="cfp_url",
            field=models.CharField(default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="tracksettings",
            name="mail",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
