# Generated by Django 4.2.5 on 2023-12-05 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0017_created_updated_everywhere"),
        ("devroom_settings", "0003_delete_trackmanager"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="schedule.room"
                    ),
                ),
            ],
        ),
    ]
