# Generated by Django 4.2.5 on 2023-12-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devroom_settings", "0005_usersettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="visible",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="matrix_id",
            field=models.CharField(default=""),
        ),
    ]
