# Generated by Django 4.2.5 on 2024-02-02 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0074_created_updated_everywhere"),
        ("devroom_settings", "0007_delete_usersettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="FosdemFeedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "personal_knowledge",
                    models.IntegerField(
                        choices=[
                            (5, "Very Good"),
                            (4, "Good"),
                            (3, "Neutral"),
                            (2, "Bad"),
                            (1, "Very Bad"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "content_importance",
                    models.IntegerField(
                        choices=[
                            (5, "Very Important"),
                            (4, "Important"),
                            (3, "Neutral"),
                            (2, "Not Important"),
                            (1, "Irrelevant"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "content_quality",
                    models.IntegerField(
                        choices=[
                            (5, "Very Good"),
                            (4, "Good"),
                            (3, "Neutral"),
                            (2, "Bad"),
                            (1, "Very Bad"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "presentation_quality",
                    models.IntegerField(
                        choices=[
                            (5, "Very Good"),
                            (4, "Good"),
                            (3, "Neutral"),
                            (2, "Bad"),
                            (1, "Very Bad"),
                        ],
                        null=True,
                    ),
                ),
                ("feedback", models.TextField()),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submission.submission",
                    ),
                ),
            ],
        ),
    ]
