# Generated by Django 4.2.5 on 2024-01-31 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0075_user_matrix_id"),
        ("devroom_settings", "0007_delete_usersettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="FosdemFeedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("personal_knowledge", models.IntegerField(null=True)),
                ("content_importance", models.IntegerField(null=True)),
                ("content_quality", models.IntegerField(null=True)),
                ("presentation_quality", models.IntegerField(null=True)),
                ("feedback", models.TextField()),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submission.submission",
                    ),
                ),
            ],
        ),
    ]
