# Generated by Django 4.2.5 on 2024-02-02 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devroom_settings", "0008_fosdemfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="fosdemfeedback",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="fosdemfeedback",
            table="fosdem_feedback",
        ),
    ]
