# Generated by Django 4.2.5 on 2024-02-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "devroom_settings",
            "0009_fosdemfeedback_timestamp_alter_fosdemfeedback_table",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="roomsettings",
            name="control_password_1",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="roomsettings",
            name="control_password_2",
            field=models.CharField(null=True),
        ),
    ]
