# Generated by Django 5.1.3 on 2025-07-06 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devroom_settings", "0013_fosdemuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FosdemUser",
        ),
    ]
