# Generated by Django 5.1.12 on 2025-11-06 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devroom_settings", "0014_delete_fosdemuser"),
        ("submission", "0078_submission_on_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracksettings",
            name="proposal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devroom_proposal",
                to="submission.submission",
            ),
        ),
    ]
