# Generated by Django 5.1.12 on 2025-12-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devroom_settings", "0015_tracksettings_proposal"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracksettings",
            name="on_website",
            field=models.BooleanField(default=True),
        ),
    ]
