# Generated by Django 5.1.12 on 2025-12-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devroom_settings", "0016_tracksettings_on_website"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roomsettings",
            old_name="control_password",
            new_name="control_password_day1",
        ),
        migrations.AddField(
            model_name="roomsettings",
            name="control_password_day2",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
