# Generated by Django 4.2.5 on 2024-11-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pretalx_fringe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fringeactivity",
            name="ends",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="fringeactivity",
            name="starts",
            field=models.DateField(),
        ),
    ]
