# Generated by Django 4.2.5 on 2024-11-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pretalx_fringe", "0002_alter_fringeactivity_ends_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fringeactivity",
            name="sort_order",
            field=models.IntegerField(null=True),
        ),
    ]
