# Generated by Django 5.1.3 on 2025-01-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pretalx_fringe", "0003_fringeactivity_sort_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fringeactivity",
            name="online",
            field=models.CharField(default="unhandled", max_length=10),
        ),
    ]
