[project]
name = "fosdem-registration"
dynamic = ["version"]
description = "pretalx plugin for FOSDEM registration"
readme = "README.rst"
license = {text = "Apache Software License"}
keywords = ["pretalx"]
authors = [
  {name = "Johan Van de Wauw", email = "johanvdw@fosdem.org"},
]
maintainers = [
  {name = "Johan Van de Wauw", email = "johanvdw@fosdem.org"},
]

dependencies = []

[project.urls]
homepage = "https://github.com/FOSDEM/pretalx-integration/fosdem_registration"
repository = "https://github.com/FOSDEM/pretalx-integration/fosdem_registration.git"

[project.entry-points."pretalx.plugin"]
fosdem_registration = "fosdem_registration:PretalxPluginMeta"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
version = {attr = "fosdem_registration.__version__"}

[tool.setuptools.packages.find]
include = ["pretalx*"]

[tool.check-manifest]
ignore = [".*"]
