# Generated by Django 4.2.5 on 2023-11-01 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("submission", "0074_created_updated_everywhere"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackSettings",
            fields=[
                (
                    "track_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="submission.track",
                    ),
                ),
                ("slug", models.SlugField(max_length=63)),
                ("mail", models.EmailField(max_length=254)),
                ("online_qa", models.BooleanField()),
            ],
            options={
                "abstract": False,
            },
            bases=("submission.track",),
        ),
    ]
