# Generated by Django 4.2.5 on 2024-01-06 02:09

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pretalx_auditlog", "0009_remove_mailtemplateproxy_snapshot_insert_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="userproxy",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="userproxy",
            name="snapshot_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="userproxy",
            name="beforedelete",
        ),
        migrations.AddField(
            model_name="userproxyevent",
            name="matrix_id",
            field=models.CharField(default="", max_length=120),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="userproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pretalx_auditlog_userproxyevent" ("avatar", "code", "email", "get_gravatar", "id", "is_active", "is_administrator", "is_staff", "is_superuser", "last_login", "locale", "matrix_id", "name", "nick", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pw_reset_time", "pw_reset_token", "timezone") VALUES (NEW."avatar", NEW."code", NEW."email", NEW."get_gravatar", NEW."id", NEW."is_active", NEW."is_administrator", NEW."is_staff", NEW."is_superuser", NEW."last_login", NEW."locale", NEW."matrix_id", NEW."name", NEW."nick", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."pw_reset_time", NEW."pw_reset_token", NEW."timezone"); RETURN NULL;',
                    hash="9af6ce26dffedc0c059af9297680a87f5353fda1",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_7392b",
                    table="person_user",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="userproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."last_login" IS DISTINCT FROM (NEW."last_login") OR OLD."code" IS DISTINCT FROM (NEW."code") OR OLD."nick" IS DISTINCT FROM (NEW."nick") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."matrix_id" IS DISTINCT FROM (NEW."matrix_id") OR OLD."is_active" IS DISTINCT FROM (NEW."is_active") OR OLD."is_staff" IS DISTINCT FROM (NEW."is_staff") OR OLD."is_administrator" IS DISTINCT FROM (NEW."is_administrator") OR OLD."is_superuser" IS DISTINCT FROM (NEW."is_superuser") OR OLD."locale" IS DISTINCT FROM (NEW."locale") OR OLD."timezone" IS DISTINCT FROM (NEW."timezone") OR OLD."avatar" IS DISTINCT FROM (NEW."avatar") OR OLD."get_gravatar" IS DISTINCT FROM (NEW."get_gravatar") OR OLD."pw_reset_token" IS DISTINCT FROM (NEW."pw_reset_token") OR OLD."pw_reset_time" IS DISTINCT FROM (NEW."pw_reset_time"))',
                    func='INSERT INTO "pretalx_auditlog_userproxyevent" ("avatar", "code", "email", "get_gravatar", "id", "is_active", "is_administrator", "is_staff", "is_superuser", "last_login", "locale", "matrix_id", "name", "nick", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pw_reset_time", "pw_reset_token", "timezone") VALUES (NEW."avatar", NEW."code", NEW."email", NEW."get_gravatar", NEW."id", NEW."is_active", NEW."is_administrator", NEW."is_staff", NEW."is_superuser", NEW."last_login", NEW."locale", NEW."matrix_id", NEW."name", NEW."nick", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."pw_reset_time", NEW."pw_reset_token", NEW."timezone"); RETURN NULL;',
                    hash="0bdf7b664213738a47bcaf114d2dceabe2dcb3e2",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_f6b5c",
                    table="person_user",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="userproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="beforedelete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pretalx_auditlog_userproxyevent" ("avatar", "code", "email", "get_gravatar", "id", "is_active", "is_administrator", "is_staff", "is_superuser", "last_login", "locale", "matrix_id", "name", "nick", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pw_reset_time", "pw_reset_token", "timezone") VALUES (OLD."avatar", OLD."code", OLD."email", OLD."get_gravatar", OLD."id", OLD."is_active", OLD."is_administrator", OLD."is_staff", OLD."is_superuser", OLD."last_login", OLD."locale", OLD."matrix_id", OLD."name", OLD."nick", _pgh_attach_context(), NOW(), \'beforedelete\', OLD."id", OLD."pw_reset_time", OLD."pw_reset_token", OLD."timezone"); RETURN NULL;',
                    hash="a1bd4153f255bb2fbf67a2072506e90a5309b917",
                    operation="DELETE",
                    pgid="pgtrigger_beforedelete_01ad6",
                    table="person_user",
                    when="AFTER",
                ),
            ),
        ),
    ]
