# Generated by Django 4.2.5 on 2024-02-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pretalx_auditlog", "0011_user_matrix_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourceproxyevent",
            name="link",
            field=models.URLField(max_length=400, null=True),
        ),
    ]
