# Generated by Django 5.1.3 on 2024-12-12 21:42

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pretalx_auditlog", "0015_remove_activitylogproxyevent_content_type_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="userproxy",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="userproxy",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="userproxy",
            name="delete_delete",
        ),
        migrations.RemoveField(
            model_name="userproxyevent",
            name="pw_reset_token",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="userproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pretalx_auditlog_userproxyevent" ("avatar", "avatar_thumbnail", "avatar_thumbnail_tiny", "code", "email", "get_gravatar", "id", "is_active", "is_administrator", "is_staff", "is_superuser", "last_login", "locale", "matrix_id", "name", "nick", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pw_reset_time", "timezone") VALUES (NEW."avatar", NEW."avatar_thumbnail", NEW."avatar_thumbnail_tiny", NEW."code", NEW."email", NEW."get_gravatar", NEW."id", NEW."is_active", NEW."is_administrator", NEW."is_staff", NEW."is_superuser", NEW."last_login", NEW."locale", NEW."matrix_id", NEW."name", NEW."nick", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."pw_reset_time", NEW."timezone"); RETURN NULL;',
                    hash="1f57e109f9cd0e576a625c3156e8248d771cc33c",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_39385",
                    table="person_user",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="userproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."avatar" IS DISTINCT FROM (NEW."avatar") OR OLD."avatar_thumbnail" IS DISTINCT FROM (NEW."avatar_thumbnail") OR OLD."avatar_thumbnail_tiny" IS DISTINCT FROM (NEW."avatar_thumbnail_tiny") OR OLD."code" IS DISTINCT FROM (NEW."code") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."get_gravatar" IS DISTINCT FROM (NEW."get_gravatar") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."is_active" IS DISTINCT FROM (NEW."is_active") OR OLD."is_administrator" IS DISTINCT FROM (NEW."is_administrator") OR OLD."is_staff" IS DISTINCT FROM (NEW."is_staff") OR OLD."is_superuser" IS DISTINCT FROM (NEW."is_superuser") OR OLD."last_login" IS DISTINCT FROM (NEW."last_login") OR OLD."locale" IS DISTINCT FROM (NEW."locale") OR OLD."matrix_id" IS DISTINCT FROM (NEW."matrix_id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."nick" IS DISTINCT FROM (NEW."nick") OR OLD."pw_reset_time" IS DISTINCT FROM (NEW."pw_reset_time") OR OLD."timezone" IS DISTINCT FROM (NEW."timezone"))',
                    func='INSERT INTO "pretalx_auditlog_userproxyevent" ("avatar", "avatar_thumbnail", "avatar_thumbnail_tiny", "code", "email", "get_gravatar", "id", "is_active", "is_administrator", "is_staff", "is_superuser", "last_login", "locale", "matrix_id", "name", "nick", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pw_reset_time", "timezone") VALUES (NEW."avatar", NEW."avatar_thumbnail", NEW."avatar_thumbnail_tiny", NEW."code", NEW."email", NEW."get_gravatar", NEW."id", NEW."is_active", NEW."is_administrator", NEW."is_staff", NEW."is_superuser", NEW."last_login", NEW."locale", NEW."matrix_id", NEW."name", NEW."nick", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."pw_reset_time", NEW."timezone"); RETURN NULL;',
                    hash="900666df8e9adc0b3bdb517cfd867972fd980438",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_16334",
                    table="person_user",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="userproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pretalx_auditlog_userproxyevent" ("avatar", "avatar_thumbnail", "avatar_thumbnail_tiny", "code", "email", "get_gravatar", "id", "is_active", "is_administrator", "is_staff", "is_superuser", "last_login", "locale", "matrix_id", "name", "nick", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pw_reset_time", "timezone") VALUES (OLD."avatar", OLD."avatar_thumbnail", OLD."avatar_thumbnail_tiny", OLD."code", OLD."email", OLD."get_gravatar", OLD."id", OLD."is_active", OLD."is_administrator", OLD."is_staff", OLD."is_superuser", OLD."last_login", OLD."locale", OLD."matrix_id", OLD."name", OLD."nick", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."pw_reset_time", OLD."timezone"); RETURN NULL;',
                    hash="58739d436b4dfcbdd13e855754ccbd72c0a5ab8a",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_152f1",
                    table="person_user",
                    when="AFTER",
                ),
            ),
        ),
    ]
