# Generated by Django 5.1.3 on 2025-01-04 22:49

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pretalx_auditlog", "0017_remove_talkslotproxy_insert_insert_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="eventproxy",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="eventproxy",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="eventproxy",
            name="delete_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="mailtemplateproxy",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="mailtemplateproxy",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="mailtemplateproxy",
            name="delete_delete",
        ),
        migrations.RemoveField(
            model_name="eventproxyevent",
            name="accept_template",
        ),
        migrations.RemoveField(
            model_name="eventproxyevent",
            name="ack_template",
        ),
        migrations.RemoveField(
            model_name="eventproxyevent",
            name="question_template",
        ),
        migrations.RemoveField(
            model_name="eventproxyevent",
            name="reject_template",
        ),
        migrations.RemoveField(
            model_name="eventproxyevent",
            name="update_template",
        ),
        migrations.AddField(
            model_name="mailtemplateproxyevent",
            name="role",
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="eventproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pretalx_auditlog_eventproxyevent" ("content_locale_array", "created", "custom_css", "custom_domain", "date_from", "date_to", "display_settings", "email", "feature_flags", "featured_sessions_text", "header_image", "id", "is_public", "landing_page_text", "locale", "locale_array", "logo", "mail_settings", "name", "organiser_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plugins", "primary_color", "review_settings", "slug", "timezone") VALUES (NEW."content_locale_array", NEW."created", NEW."custom_css", NEW."custom_domain", NEW."date_from", NEW."date_to", NEW."display_settings", NEW."email", NEW."feature_flags", NEW."featured_sessions_text", NEW."header_image", NEW."id", NEW."is_public", NEW."landing_page_text", NEW."locale", NEW."locale_array", NEW."logo", NEW."mail_settings", NEW."name", NEW."organiser_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."plugins", NEW."primary_color", NEW."review_settings", NEW."slug", NEW."timezone"); RETURN NULL;',
                    hash="e60f772eae95b2ccbc50a43d09d78f61bebc2b2f",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_932e5",
                    table="event_event",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="eventproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."content_locale_array" IS DISTINCT FROM (NEW."content_locale_array") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."custom_css" IS DISTINCT FROM (NEW."custom_css") OR OLD."custom_domain" IS DISTINCT FROM (NEW."custom_domain") OR OLD."date_from" IS DISTINCT FROM (NEW."date_from") OR OLD."date_to" IS DISTINCT FROM (NEW."date_to") OR OLD."display_settings" IS DISTINCT FROM (NEW."display_settings") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."feature_flags" IS DISTINCT FROM (NEW."feature_flags") OR OLD."featured_sessions_text" IS DISTINCT FROM (NEW."featured_sessions_text") OR OLD."header_image" IS DISTINCT FROM (NEW."header_image") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."is_public" IS DISTINCT FROM (NEW."is_public") OR OLD."landing_page_text" IS DISTINCT FROM (NEW."landing_page_text") OR OLD."locale" IS DISTINCT FROM (NEW."locale") OR OLD."locale_array" IS DISTINCT FROM (NEW."locale_array") OR OLD."logo" IS DISTINCT FROM (NEW."logo") OR OLD."mail_settings" IS DISTINCT FROM (NEW."mail_settings") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."organiser_id" IS DISTINCT FROM (NEW."organiser_id") OR OLD."plugins" IS DISTINCT FROM (NEW."plugins") OR OLD."primary_color" IS DISTINCT FROM (NEW."primary_color") OR OLD."review_settings" IS DISTINCT FROM (NEW."review_settings") OR OLD."slug" IS DISTINCT FROM (NEW."slug") OR OLD."timezone" IS DISTINCT FROM (NEW."timezone"))',
                    func='INSERT INTO "pretalx_auditlog_eventproxyevent" ("content_locale_array", "created", "custom_css", "custom_domain", "date_from", "date_to", "display_settings", "email", "feature_flags", "featured_sessions_text", "header_image", "id", "is_public", "landing_page_text", "locale", "locale_array", "logo", "mail_settings", "name", "organiser_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plugins", "primary_color", "review_settings", "slug", "timezone") VALUES (NEW."content_locale_array", NEW."created", NEW."custom_css", NEW."custom_domain", NEW."date_from", NEW."date_to", NEW."display_settings", NEW."email", NEW."feature_flags", NEW."featured_sessions_text", NEW."header_image", NEW."id", NEW."is_public", NEW."landing_page_text", NEW."locale", NEW."locale_array", NEW."logo", NEW."mail_settings", NEW."name", NEW."organiser_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."plugins", NEW."primary_color", NEW."review_settings", NEW."slug", NEW."timezone"); RETURN NULL;',
                    hash="b982b38b0a5429183bed6a2ba718587ba7e70af0",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_cbff6",
                    table="event_event",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="eventproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pretalx_auditlog_eventproxyevent" ("content_locale_array", "created", "custom_css", "custom_domain", "date_from", "date_to", "display_settings", "email", "feature_flags", "featured_sessions_text", "header_image", "id", "is_public", "landing_page_text", "locale", "locale_array", "logo", "mail_settings", "name", "organiser_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plugins", "primary_color", "review_settings", "slug", "timezone") VALUES (OLD."content_locale_array", OLD."created", OLD."custom_css", OLD."custom_domain", OLD."date_from", OLD."date_to", OLD."display_settings", OLD."email", OLD."feature_flags", OLD."featured_sessions_text", OLD."header_image", OLD."id", OLD."is_public", OLD."landing_page_text", OLD."locale", OLD."locale_array", OLD."logo", OLD."mail_settings", OLD."name", OLD."organiser_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."plugins", OLD."primary_color", OLD."review_settings", OLD."slug", OLD."timezone"); RETURN NULL;',
                    hash="1d117d54e3addf6abb665ff948dbb5415f36e422",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_da614",
                    table="event_event",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="mailtemplateproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pretalx_auditlog_mailtemplateproxyevent" ("bcc", "cc", "created", "event_id", "id", "is_auto_created", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reply_to", "role", "subject", "text", "updated") VALUES (NEW."bcc", NEW."cc", NEW."created", NEW."event_id", NEW."id", NEW."is_auto_created", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reply_to", NEW."role", NEW."subject", NEW."text", NEW."updated"); RETURN NULL;',
                    hash="36ccd673c9fa46b7ac99197d75e746ea564d8aaa",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_7ccdb",
                    table="mail_mailtemplate",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="mailtemplateproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "pretalx_auditlog_mailtemplateproxyevent" ("bcc", "cc", "created", "event_id", "id", "is_auto_created", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reply_to", "role", "subject", "text", "updated") VALUES (NEW."bcc", NEW."cc", NEW."created", NEW."event_id", NEW."id", NEW."is_auto_created", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reply_to", NEW."role", NEW."subject", NEW."text", NEW."updated"); RETURN NULL;',
                    hash="0caef68a3ecc03256009e42775839673dddac41f",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_9c223",
                    table="mail_mailtemplate",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="mailtemplateproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pretalx_auditlog_mailtemplateproxyevent" ("bcc", "cc", "created", "event_id", "id", "is_auto_created", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reply_to", "role", "subject", "text", "updated") VALUES (OLD."bcc", OLD."cc", OLD."created", OLD."event_id", OLD."id", OLD."is_auto_created", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."reply_to", OLD."role", OLD."subject", OLD."text", OLD."updated"); RETURN NULL;',
                    hash="d762b04470bbacac378af2146509f0305fef67eb",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_a05db",
                    table="mail_mailtemplate",
                    when="AFTER",
                ),
            ),
        ),
    ]
