# Generated by Django 5.1.12 on 2025-11-14 21:43

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pretalx_auditlog", "0018_remove_eventproxy_insert_insert_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="submissionproxy",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="submissionproxy",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="submissionproxy",
            name="delete_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="tagproxy",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="tagproxy",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="tagproxy",
            name="delete_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="userproxy",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="userproxy",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="userproxy",
            name="delete_delete",
        ),
        migrations.RenameField(
            model_name="tagproxyevent",
            old_name="public",
            new_name="is_public",
        ),
        migrations.RemoveField(
            model_name="submissionproxyevent",
            name="on_website",
        ),
        migrations.RemoveField(
            model_name="userproxyevent",
            name="matrix_id",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="submissionproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pretalx_auditlog_submissionproxyevent" ("abstract", "access_code_id", "anonymised_data", "code", "content_locale", "created", "description", "do_not_record", "duration", "event_id", "id", "image", "internal_notes", "is_featured", "notes", "pending_state", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "review_code", "slot_count", "state", "submission_type_id", "title", "track_id") VALUES (NEW."abstract", NEW."access_code_id", NEW."anonymised_data", NEW."code", NEW."content_locale", NEW."created", NEW."description", NEW."do_not_record", NEW."duration", NEW."event_id", NEW."id", NEW."image", NEW."internal_notes", NEW."is_featured", NEW."notes", NEW."pending_state", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."review_code", NEW."slot_count", NEW."state", NEW."submission_type_id", NEW."title", NEW."track_id"); RETURN NULL;',
                    hash="141267261ef2bb999246ffa182f74210edb7fe70",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_c03d8",
                    table="submission_submission",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="submissionproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."abstract" IS DISTINCT FROM (NEW."abstract") OR OLD."access_code_id" IS DISTINCT FROM (NEW."access_code_id") OR OLD."anonymised_data" IS DISTINCT FROM (NEW."anonymised_data") OR OLD."code" IS DISTINCT FROM (NEW."code") OR OLD."content_locale" IS DISTINCT FROM (NEW."content_locale") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."do_not_record" IS DISTINCT FROM (NEW."do_not_record") OR OLD."duration" IS DISTINCT FROM (NEW."duration") OR OLD."event_id" IS DISTINCT FROM (NEW."event_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."image" IS DISTINCT FROM (NEW."image") OR OLD."internal_notes" IS DISTINCT FROM (NEW."internal_notes") OR OLD."is_featured" IS DISTINCT FROM (NEW."is_featured") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."pending_state" IS DISTINCT FROM (NEW."pending_state") OR OLD."review_code" IS DISTINCT FROM (NEW."review_code") OR OLD."slot_count" IS DISTINCT FROM (NEW."slot_count") OR OLD."state" IS DISTINCT FROM (NEW."state") OR OLD."submission_type_id" IS DISTINCT FROM (NEW."submission_type_id") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."track_id" IS DISTINCT FROM (NEW."track_id"))',
                    func='INSERT INTO "pretalx_auditlog_submissionproxyevent" ("abstract", "access_code_id", "anonymised_data", "code", "content_locale", "created", "description", "do_not_record", "duration", "event_id", "id", "image", "internal_notes", "is_featured", "notes", "pending_state", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "review_code", "slot_count", "state", "submission_type_id", "title", "track_id") VALUES (NEW."abstract", NEW."access_code_id", NEW."anonymised_data", NEW."code", NEW."content_locale", NEW."created", NEW."description", NEW."do_not_record", NEW."duration", NEW."event_id", NEW."id", NEW."image", NEW."internal_notes", NEW."is_featured", NEW."notes", NEW."pending_state", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."review_code", NEW."slot_count", NEW."state", NEW."submission_type_id", NEW."title", NEW."track_id"); RETURN NULL;',
                    hash="51781a91409801841b93616be70cf59c0a9e5814",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_0bc27",
                    table="submission_submission",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="submissionproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pretalx_auditlog_submissionproxyevent" ("abstract", "access_code_id", "anonymised_data", "code", "content_locale", "created", "description", "do_not_record", "duration", "event_id", "id", "image", "internal_notes", "is_featured", "notes", "pending_state", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "review_code", "slot_count", "state", "submission_type_id", "title", "track_id") VALUES (OLD."abstract", OLD."access_code_id", OLD."anonymised_data", OLD."code", OLD."content_locale", OLD."created", OLD."description", OLD."do_not_record", OLD."duration", OLD."event_id", OLD."id", OLD."image", OLD."internal_notes", OLD."is_featured", OLD."notes", OLD."pending_state", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."review_code", OLD."slot_count", OLD."state", OLD."submission_type_id", OLD."title", OLD."track_id"); RETURN NULL;',
                    hash="16504edbe0716c2c559d42ed17e3a8862ccbe5b3",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_4b93d",
                    table="submission_submission",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="tagproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pretalx_auditlog_tagproxyevent" ("color", "created", "description", "event_id", "id", "is_public", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tag", "updated") VALUES (NEW."color", NEW."created", NEW."description", NEW."event_id", NEW."id", NEW."is_public", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."tag", NEW."updated"); RETURN NULL;',
                    hash="3663427a34ebc923261a988459ba5609d558339c",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_70e00",
                    table="submission_tag",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="tagproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "pretalx_auditlog_tagproxyevent" ("color", "created", "description", "event_id", "id", "is_public", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tag", "updated") VALUES (NEW."color", NEW."created", NEW."description", NEW."event_id", NEW."id", NEW."is_public", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."tag", NEW."updated"); RETURN NULL;',
                    hash="df85fa22bc2dfb5ea2d45112b4d4e9c9a39354b6",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_73576",
                    table="submission_tag",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="tagproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pretalx_auditlog_tagproxyevent" ("color", "created", "description", "event_id", "id", "is_public", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tag", "updated") VALUES (OLD."color", OLD."created", OLD."description", OLD."event_id", OLD."id", OLD."is_public", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."tag", OLD."updated"); RETURN NULL;',
                    hash="97cbaba5fdc8e33ee9be407be4e4851db5e6caef",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_6de5d",
                    table="submission_tag",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="userproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pretalx_auditlog_userproxyevent" ("avatar", "avatar_thumbnail", "avatar_thumbnail_tiny", "code", "email", "get_gravatar", "id", "is_active", "is_administrator", "is_staff", "is_superuser", "last_login", "locale", "name", "nick", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pw_reset_time", "timezone") VALUES (NEW."avatar", NEW."avatar_thumbnail", NEW."avatar_thumbnail_tiny", NEW."code", NEW."email", NEW."get_gravatar", NEW."id", NEW."is_active", NEW."is_administrator", NEW."is_staff", NEW."is_superuser", NEW."last_login", NEW."locale", NEW."name", NEW."nick", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."pw_reset_time", NEW."timezone"); RETURN NULL;',
                    hash="705d4d2d5565321dd19551986e6e11ea0f4551f2",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_39385",
                    table="person_user",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="userproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."avatar" IS DISTINCT FROM (NEW."avatar") OR OLD."avatar_thumbnail" IS DISTINCT FROM (NEW."avatar_thumbnail") OR OLD."avatar_thumbnail_tiny" IS DISTINCT FROM (NEW."avatar_thumbnail_tiny") OR OLD."code" IS DISTINCT FROM (NEW."code") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."get_gravatar" IS DISTINCT FROM (NEW."get_gravatar") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."is_active" IS DISTINCT FROM (NEW."is_active") OR OLD."is_administrator" IS DISTINCT FROM (NEW."is_administrator") OR OLD."is_staff" IS DISTINCT FROM (NEW."is_staff") OR OLD."is_superuser" IS DISTINCT FROM (NEW."is_superuser") OR OLD."last_login" IS DISTINCT FROM (NEW."last_login") OR OLD."locale" IS DISTINCT FROM (NEW."locale") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."nick" IS DISTINCT FROM (NEW."nick") OR OLD."pw_reset_time" IS DISTINCT FROM (NEW."pw_reset_time") OR OLD."timezone" IS DISTINCT FROM (NEW."timezone"))',
                    func='INSERT INTO "pretalx_auditlog_userproxyevent" ("avatar", "avatar_thumbnail", "avatar_thumbnail_tiny", "code", "email", "get_gravatar", "id", "is_active", "is_administrator", "is_staff", "is_superuser", "last_login", "locale", "name", "nick", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pw_reset_time", "timezone") VALUES (NEW."avatar", NEW."avatar_thumbnail", NEW."avatar_thumbnail_tiny", NEW."code", NEW."email", NEW."get_gravatar", NEW."id", NEW."is_active", NEW."is_administrator", NEW."is_staff", NEW."is_superuser", NEW."last_login", NEW."locale", NEW."name", NEW."nick", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."pw_reset_time", NEW."timezone"); RETURN NULL;',
                    hash="dc1f09ffe2745cb79578e8af5e209bb0242d398c",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_16334",
                    table="person_user",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="userproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pretalx_auditlog_userproxyevent" ("avatar", "avatar_thumbnail", "avatar_thumbnail_tiny", "code", "email", "get_gravatar", "id", "is_active", "is_administrator", "is_staff", "is_superuser", "last_login", "locale", "name", "nick", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pw_reset_time", "timezone") VALUES (OLD."avatar", OLD."avatar_thumbnail", OLD."avatar_thumbnail_tiny", OLD."code", OLD."email", OLD."get_gravatar", OLD."id", OLD."is_active", OLD."is_administrator", OLD."is_staff", OLD."is_superuser", OLD."last_login", OLD."locale", OLD."name", OLD."nick", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."pw_reset_time", OLD."timezone"); RETURN NULL;',
                    hash="7a4df0b0845f3d47ba57fb7446507b3488d892dd",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_152f1",
                    table="person_user",
                    when="AFTER",
                ),
            ),
        ),
    ]
