# Generated by Django 5.1.12 on 2025-11-30 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("event", "0039_alter_teaminvite_token"),
        ("submission", "0081_alter_tag_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="FosdemRegistrationGuardian",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, help_text="Name of parent or guardian"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        help_text="Email address of parent or guardian. Registration confirmation will be sent here",
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        max_length=20,
                        help_text="Emergency phone number of parent or guardian",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FosdemRegistration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        max_length=100, help_text="child name or nickname"
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        help_text="age in years of child on the day of the session"
                    ),
                ),
                ("special_needs", models.CharField(max_length=400, blank=True)),
                (
                    "removed",
                    models.BooleanField(
                        default=False, help_text="registration removed"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submission.submission",
                    ),
                ),
                (
                    "registering_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fosdem_registration.fosdemregistrationguardian",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FosdemRegistrationTrack",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "max_number_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submission.question",
                    ),
                ),
                ("teams", models.ManyToManyField(to="event.team")),
                (
                    "track",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submission.track",
                    ),
                ),
            ],
        ),
    ]
