# Generated by Django 5.1.12 on 2025-11-15 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("event", "0039_alter_teaminvite_token"),
        ("submission", "0081_alter_tag_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FosdemRegistration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("nickname", models.CharField()),
                ("age", models.IntegerField()),
                (
                    "registering_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submission.submission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FosdemRegistrationTrack",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "max_number_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submission.question",
                    ),
                ),
                ("teams", models.ManyToManyField(to="event.team")),
                (
                    "track",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submission.track",
                    ),
                ),
            ],
        ),
    ]
