# Generated by Django 5.1.12 on 2026-01-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fosdem_registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fosdemregistration",
            name="removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fosdemregistration",
            name="nickname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="fosdemregistration",
            name="special_needs",
            field=models.CharField(max_length=400),
        ),
    ]
