# Generated by Django 5.1.3 on 2025-01-28 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TalkSuggestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("why", models.TextField()),
                ("speaker_connection", models.TextField()),
                ("contact", models.EmailField(max_length=254, null=True)),
                ("other", models.TextField()),
                ("internal_notes", models.TextField()),
                ("sort_order", models.IntegerField(null=True)),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
    ]
